name: 'Create Stencil Sass Archive Upload'
description: 'compresses and uploads an archive to be reused across jobs'
inputs:
  paths:
    description: 'paths to files or directories to archive (recursive)'
  output:
    description: 'output file name'
  name:
    description: 'name of the archive to upload'
runs:
  using: 'composite'
  steps:
    - name: Create Archive
      run: zip -q -r ${{ inputs.output }} ${{ inputs.paths }}
      shell: bash

    - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.output }}
