name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node from Volta
      uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
      with:
        node-version-file: 'package.json'
        cache: 'npm'
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        npm install
        npm run build -- --ci
        npm run test.ci
      env:
        CI: true