name: 'Get Core Dependencies'
description: 'sets the node version & initializes core dependencies'
runs:
  using: composite
  steps:
    # this overrides previous versions of the node runtime that was set.
    # jobs that need a different version of the Node runtime should explicitly
    # set their node version after running this step
    - name: Use Node Version from Volta
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        node-version-file: './package.json'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash
